#include:
#  - project: 'tif/infra/charts/chart-registry'
#    file: '/templates/PublishChart.gitlab-ci.yml'
#    ref: master
    
variables:
  NEXUS_CHARTS_DIR: "https://ceiser-wbench.psst.t-online.corp/nexus3/repository/tif-public-raw/tif/infr/charts"

stages:
  - publish

.check_mandantory_variables: &check_mandantory_variables |
  if [ ! "$TIF_NEXUS_USER" ]; then echo "Error: \$TIF_NEXUS_USER must be set!"; exit 1; fi
  if [ ! "$TIF_NEXUS_PASSWORD" ]; then echo "Error: \$TIF_NEXUS_PASSWORD must be set!"; exit 1; fi

.setup_job_basics: &setup_job_basics
  before_script:
    - *check_mandantory_variables
  tags:
    - run01_docker

.add_packages: &add_packages |
  apt-get update && apt-get install -y --no-install-recommends curl
  pip install --upgrade pip setuptools
  pip install --upgrade httpie
  curl -L https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

.package_chart: &package_chart |
  CHART_VERSION="$CI_COMMIT_REF_NAME"

  VERSION_REGEX='^[0-9]+\.[0-9]+\.[0-9]+$'
  if ! [[ $CHART_VERSION =~ $VERSION_REGEX ]] ; then
    CHART_VERSION="0.0.0-$CI_COMMIT_REF_NAME"
  fi
  if [ -f "Chart.yaml" ]; then
    CHART_NAME=`yq r Chart.yaml name`
    yq w -i Chart.yaml version "$CHART_VERSION"
  else
    echo "Error: Chart.yaml could not be found."; exit 1;
  fi
    
  mkdir /tmp/$CHART_NAME
  cp -r * /tmp/$CHART_NAME
  CHART_FILE="$CHART_NAME-$CHART_VERSION.tgz"
  pushd /tmp
    tar cfvz $CHART_FILE $CHART_NAME
  popd
  mv /tmp/$CHART_FILE .

publish:
  extends: .setup_job_basics
  stage: publish
  image: 'python:3-slim'
  except:
    - master
  script:
    - *add_packages
    - *package_chart
    - http --verify=no -a $TIF_NEXUS_USER:$TIF_NEXUS_PASSWORD PUT $NEXUS_CHARTS_DIR/$CHART_NAME/$CHART_VERSION/$CHART_FILE < $CHART_FILE
