apiVersion: v2
name: iris
version: 5.5.1
appVersion: 16.1.1
description: Iris provided by ENI
keywords:
- eni
- tardis
- iris
- keycloak
dependencies:
- name: postgresql
  version: 1.0.0
maintainers:
- name: Tardis
  email: tardis@telekom.de