apiVersion: v2
name: iris
version: 5.3.0
appVersion: 16.1.1
description: Iris provided by ENI-Hub
keywords:
- enihub
- tardis
- iris
- keycloak
dependencies:
- name: postgresql
  version: 1.0.0
maintainers:
- name: Christian Stein
  email: steinc@external.telekom.de
- name: Georg Teichert-Matuschek
  email: Georg.Teichert-Matuschek@external.telekom.de
