global:
  platform: kubernetes
  storageclass: gp2
  domain: ""
  labels:
    # fluentd label
    tif.telekom.de/group: tif
  ingress:
    annotations: {}
      # external-dns.alpha.kubernetes.io/target: ""
      # kubernetes.io/ingress.class: ""

  # If imagePullSecrets is not empty, a pull secret will be deployed for each entry otherwise 
  # no pull secret will be deployed
  # If you use Sapling for deployment this will be set automatically
  imagePullSecrets: []
  #- name: mtr-tif-public
  #  registry: https://mtr.external.otc.telekomcloud.com
  #  username: changeme
  #  password: changeme
      
  db:
    database: 'sso'
    username: 'sso'
    password: 'SEE SECRETS'
    admin_username: 'postgres'
    admin_password: 'SEE SECRETS'

  externalDatabase:
    enabled: false
    # host: ''
    # ssl: false
    # sslMode: 'verify-full'
    # sslCert: |
    #   -----BEGIN CERTIFICATE-----
    #   <CA certificate in PEM format here>
    #   -----END CERTIFICATE-----
    # sslKey: |
    #   -----BEGIN PRIVATE KEY-----
    #   <pk8 in PEM format here>
    #   -----END PRIVATE KEY-----
    # sslRootCert: |
    #   -----BEGIN CERTIFICATE-----
    #   <Root certificate in PEM format here>
    #   -----END CERTIFICATE-----

securityContext: {}

admin_username: admin
admin_password: 'SEE SECRETS'
access_token_lifespan: 300

db:
  database: 'sso'
  username: 'sso'
  password: 'SEE SECRETS'
  host: 'postgresql'
  
replicas: 1

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 500Mi

ingress:
  enabled: true
  # hostname: ""
  # tlsSecret: ""
  annotations: {}

prometheus:
  enabled: true
  authToken: changeme
# port: 9542
# path: /metrics

customConfig:
  # with the following setting one can set the frontendUrl configuration for hostname SPI
  # frontendUrl: '${keycloak.frontendUrl:}'

  spi: {}
  # as alternative, one can replace the whole SPI "hostname" configuration block, however this overrides the frontendUrl variable
  # spi:
  #   hostname: |-
  #    <spi name="hostname">
  #      <!-- some xml config -->
  #    </spi>


# Overwrite Java specific options used by Keycloak Wildfly application server
javaOptions: '-XX:+UseContainerSupport -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0 -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true'

postgresql:
  securityContext: {}

  max_connections: "100"
  shared_buffers: "32MB"
  max_prepared_transactions: "100"

  # You can force using a specific image here:
  #image: 
    #repository: mtr.external.otc.telekomcloud.com
    #organization: tif-public
    #name: postgres
    #tag: 12.3-debian
  # Or use the flattened string form:
  #image: mtr.external.otc.telekomcloud.com/tif-public/postgres:12.3-debian

  replicas: 1

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 200Mi

  persistence:
    storageclass: gp2
    resources:
      requests:
        storage: 1Gi
    #mountDir: '/var/lib/postgresql/data'
    