global:
  platform: kubernetes
  project_prefix: "tif-"
  storageclass: "gp2"
  externalDnsTarget: ""
  domain: ""
    
  db:
    database: 'sso'
    username: 'sso'
    password: 'SEE SECRETS'
    admin_username: 'postgres'
    admin_password: 'SEE SECRETS'

  use_external_database: false

  # If imagePullSecrets is not empty, a pull secret will be deployed for each entry otherwise no pull secret will be deployed
  # If you use tif-infra-pipeline (TIF installer) this will be set automatically
  # imagePullSecrets:
  #   - name: mtr-tif-public
  #     registry: https://mtr.external.otc.telekomcloud.com
  #     username: changeme
  #     password: changeme
  imagePullSecrets: []

postgresql:
  max_connections: "100"
  shared_buffers: "32MB"
  max_prepared_transactions: "100"

  image:
    registry: "mtr.external.otc.telekomcloud.com"
    repository: "tif-public/postgres"
    tag: "stable"

  replicas: 1
  
  resources:
    limits:
      memory: 2G
      cpu: 2000m
    requests:
      cpu: 50m
      memory: 250M

  persistence:
    storageclass: "gp2"
    capacity: "1Gi"

keycloak:

  admin_username: admin
  admin_password: 'SEE SECRETS'
  access_token_lifespan: 300

  image:
    registry: "mtr.external.otc.telekomcloud.com"
    repository: "tif-public/tif-keycloak"
    tag: "1.0.0-RC"
    # for testing on openshift use another image
    tag_openshift: "1.0.0-RC"
    db_client_registry: "mtr.external.otc.telekomcloud.com"
    db_client_repository: "tif-public/postgres"
    db_client_tag: "stable"

  replicas: 1

  resources:
    requests:
      memory: "2Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

  ingress:
    enabled: true
    # hostname: ""
    # tlsSecret: ""
    annotations: {}

  prometheus:
    enabled: true
    authToken: changeme
  # port: 9542
  # path: /metrics
