apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "rhsso.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      deployment: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
#      annotations:
#        checksum/config: {{ include (print $.Template.BasePath "/configmap-config.yml") . | sha256sum }}
#        checksum/realm: {{ include (print $.Template.BasePath "/configmap-realm.yml") . | sha256sum }}
      labels:
        application: {{ .Release.Name }}
        deployment: {{ .Release.Name }}
      name: {{ .Release.Name }}
    spec:
      containers:
      - image: '{{ include "image.location" $ }}'
        imagePullPolicy: Always
        #command: ["/opt/jboss/tools/docker-entrypoint.sh", "-b", "0.0.0.0", "-c", "/tmp/keycloak/configs/standalone-ha.xml"]
        env:
{{ include "keycloak.db.env" $ | indent 8 }}
{{ include "keycloak.admin.env" $ | indent 8 }}
        name: rhsso
        ports:
        - { containerPort: 8080, protocol: TCP, name: http }
        - { containerPort: 8443, protocol: TCP, name: https }
#        livenessProbe:
#          httpGet:
#            path: httpGet
#            port: 8080
#        readinessProbe:
#          httpGet:
#            path: httpGet
#            port: 8080
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        volumeMounts:
        - name: realm-volume
          mountPath: /tmp/keycloak/realms
        - name: config-volume
          mountPath: /tmp/keycloak/configs
      volumes:
      - name: realm-volume
        configMap:
          name: {{ .Release.Name }}-realm
          items:
          - key: tif-realm.json
            path: tif-realm.json
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config
          items:
          - key: standalone-ha.xml
            path: standalone-ha.xml
      initContainers:
      - name: "checkdb"
        image: '{{ include "image.init.location" $ }}'
        command:
        - /bin/bash
        - -c
        - until pg_isready -U {{ include "db.username" $ | default .Values.db.username }}; do echo waiting for database; sleep 2; done;
        env:
{{ include "postgres.checkdb.env" $ | indent 8 }}
