{{- if eq .Values.global.platform "kubernetes" }}
{{- range $key, $val := .Values.global.domain }}
  {{- if $val.expose }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
{{- if $val.labels }}
{{ toYaml $val.labels | indent 4 }}
{{- end }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $.Release.Name }}-{{ include "env_short_name" $ }}.{{ tpl $val.url $ }}
    external-dns.alpha.kubernetes.io/target: {{ $.Values.global.externalDnsTarget }}
    kubernetes.io/ingress.class: external-nginx
spec:
  rules:
  - host: {{ $.Release.Name }}-{{ include "env_short_name" $ }}.{{ tpl $val.url $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
{{- if and $.Values.tls $.Values.tls.domain }}
{{- if or ((index $.Values.tls.domain $key).secret) ($.Values.tls.secret) }}
  tls:
  - secretName: {{ (index $.Values.tls.domain $key).secret | default $.Values.tls.secret }}
    hosts:
    - {{ $.Release.Name }}-{{ include "env_short_name" $ }}.{{ tpl $val.url $ }}
{{- end }}
{{- end }}
  {{- end }}
{{- end }}
{{- end }}
