{{- if eq .Values.global.platform "openshift" }}
{{- range $key, $val := .Values.global.domain }}
  {{- if $val.expose }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  labels: {{ include "rhsso.labels" $ | nindent 4 }}
{{- if $val.labels }}
{{ toYaml $val.labels | indent 4 }}
{{- end }}
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  host: {{ $.Release.Name }}-{{ include "env_short_name" $ }}.{{ tpl $val.url $ }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $.Release.Name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{ with index $.Values (tpl $val.slug $) }}
    key: |-
{{ .key | indent 6 }}
    certificate: |-
{{ .cert | indent 6 }}
    caCertificate: |-
{{ .ca | indent 6 }}
{{- end }}
status:
  ingress:
    - host: ""
  {{- end }}
{{- end }}
{{- end }}
