{{- if eq .Values.global.database.location "local" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "postgresql.selector" $ | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "postgresql.labels" $ | nindent 8 }}
      {{- include "common.status-monitor.labels" $ | nindent 8 }}
      {{- include "database.status-monitor.labels" $ | nindent 8 }}
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup | default 999 }}
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        env:
        {{- include "postgresql.env" $ | indent 8 }}
        image: '{{ include "postgresql.image" $ }}'
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext: {{ .Values.securityContext | toYaml | nindent 10 }}
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: {{ .Release.Name }}-{{ .Chart.Name }}-tmp
        - mountPath: /var/run/postgresql
          name: {{ .Release.Name }}-{{ .Chart.Name }}-run
        - mountPath: {{ .Values.persistence.mountDir | default "/var/lib/postgresql/data" }}
          name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pg_isready -U {{ .Values.global.database.username }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-run
        emptyDir: {}
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-tmp
        emptyDir: {}
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}-data
      restartPolicy: Always
{{- end }}

