# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postgresql.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" $ | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end  }}
  {{- if or .Values.pdb.maxUnavailable ( not .Values.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "postgresql.selector" . | nindent 6 }}
{{- end }}
