# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq .Values.global.database.location "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.pvcName" . }}
  finalizers: [ kubernetes.io/pvc-protection ]
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
{{- if .Values.persistence }}
  {{- if .Values.persistence.keepOnDelete }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end -}}
{{- end }}
spec:
  storageClassName: {{ include "platformSpecificValue" (list $ . ".Values.global.storageClassName") | default .Values.persistence.storageClassName | default "" }}
  accessModes:
    - ReadWriteOnce
  resources: {{ .Values.persistence.resources | toYaml | nindent 4 }}
{{- if .Values.global.volumeName }}
  volumeName: {{ .Values.global.volumeName }}
{{- end }}
{{- end }}
