apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
type: Opaque
data:
  password: {{ (.Values.global.db.password | default .Values.password) | b64enc }}
  adminPassword: {{ (.Values.global.db.admin_password | default .Values.admin_password) | b64enc }}