apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $adminPassword := dict "password" .Values.admin_password "rules" .Values.global.passwordRules }}
  adminPassword: {{ $adminPassword | include "passutil.validated" | b64enc | quote }}
  {{- $databasePassword := dict "password" .Values.global.database.password "rules" .Values.global.passwordRules }}
  databasePassword: {{ $databasePassword | include "passutil.validated" | b64enc | quote }}