apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $oldOrNewPassword := .Values.adminPassword | default .Values.admin_password }}
  {{- $adminPassword := dict "password" $oldOrNewPassword "rules" .Values.global.passwordRules }}
  adminPassword: {{ $adminPassword | include "passutil.validated" | b64enc | quote }}
  {{- $password := dict "password" (.Values.global.db.password | default .Values.password) "rules" .Values.global.passwordRules }}
  password: {{ $password | include "passutil.validated" | b64enc | quote }}
