---
{{- if not (.Values.global.externalDatabase.enabled | default .Values.externalDatabase.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:                  
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
{{- end }}

