apiVersion: v1
name: postgresql
version: 1.0.0
icon: https://www.postgresql.org/media/img/about/press/elephant.png
appVersion: 9.6.0
description: PostgreSQL (original) database provided by DHEI
keywords:
- db
- sql
- postgresql
- tif
maintainers:
- name: Mike Herwig
  email: Mike.Herwig@external.t-systems.com
- name: Georg Teichert-Matuschek
  email: Georg.Teichert-Matuschek@external.telekom.de
