# To override values - uncomment below:
global:
  metadata:
    pipeline: {}
    
  platform: kubernetes
  #storageClassName: gp2

  passwordRules:
    enabled: false
    length: 12
    mustMatch:
    - '[a-z]'
    - '[A-Z]'
    - '[0-9]'
    - '[^a-zA-Z0-9]' 

  labels:
    # fluentd label

  imagePullSecrets: []
  #- name: secret
  #  registry: https://<your-registry>
  #  username: changeme
  #  password: changeme
  imagePullPolicy: IfNotPresent

  database:
    location: local
    # Set host if you use an external database or service name is not sufficient
    #host: ''
    #port: 5432
    database: pgdb
    username: pgusr
    password: not_secure_pwd

  failOnUnsetValues: true

#image:
  #repository:
  #organization:
  #name:
  #tag:
#imagePullPolicy: IfNotPresent

#podSecurityContext:
  #fsGroup: 999
  #supplementalGroups: 999

#containerSecurityContext: {}

#adminPassword: "not_secure_pwd"

# maximum number of client connections
maxConnections: "100"

# memory dedicated to PostgreSQL for caching data
sharedBuffers: "32MB"

# maximum number of transactions that can be in the "prepared" state simultaneously
# setting this parameter to zero (default) disables the prepared-transaction feature
maxPreparedTransactions: "0"

resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 20m
    memory: 200Mi

persistence:
  keepOnDelete: false
  #storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  #mountDir: '/var/lib/postgresql/data'

deployment:
  annotations: {}
