global:
  passwordRules:
    enabled: false
    length: 12
    mustMatch:
    - '[a-z]'
    - '[A-Z]'
    - '[0-9]'
    - '[^a-zA-Z0-9]' 

  labels:
    # fluentd label
    tif.telekom.de/group: tif
    
  db: {}

  externalDatabase:
    enabled: false

  imagePullSecrets: []
  #- name: mtr-tif-public
  #  registry: https://mtr.external.otc.telekomcloud.com
  #  username: changeme
  #  password: changeme

  imagePullPolicy: IfNotPresent


securityContext: {}
  #fsGroup: 999

# database admin credentials
admin_username: "postgres"
admin_password: "changeme"

# name of the database which should be created
database: "change_me"

# credentials of user that should be created for database
username: "change_me"
password: "change_me"

# maximum number of client connections
max_connections: "100"

# memory dedicated to PostgreSQL for caching data
shared_buffers: "32MB"

# maximum number of transactions that can be in the "prepared" state simultaneously
# setting this parameter to zero (default) disables the prepared-transaction feature
max_prepared_transactions: "0"

# if set to true no objects will be created at all
externalDatabase:
  enabled: false 

image: mtr.devops.telekom.de/tardis-common/postgres:12.3-debian

resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 20m
    memory: 200Mi

persistence:
  storageclass: gp2
  resources:
    requests:
      storage: 1Gi
  #mountDir: '/var/lib/postgresql/data'

deployment:
  annotations: {}