{{- if .Values.realms -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range .Values.realms }}
  {{ $realmPath := printf "realms/%s.json" . }}
  {{- printf "%s.json" . }}: |-
    {{- tpl ($files.Get $realmPath ) $ | nindent 4 }}
  {{- end -}}
  {{- end }}
