apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "realms/*.json" }}
  {{ base $path }}: |
  {{- tpl ($.Files.Get $path) $ | nindent 4 }}
  {{- end }}
  {{- if and .Values.realms -}}
  {{- if not (eq (len .Values.realms) 0) }}
  {{- range $realmIdx, $realm := .Values.realms }}
  '_generated_{{ $realm.name }}.json': |
    {
        "id": "{{ $realm.name }}",
        "realm": "{{ $realm.name }}",
        "enabled": {{ $realm.enabled | default true }},
        "accessTokenLifespan": {{ $realm.access_token_lifespan | default 300 }},
        "eventsEnabled": true,
        "eventsListeners": [
            {{- if eq $.Values.prometheus.enabled true }}
            "metrics-listener",
            {{- end }}
            "jboss-logging"
        ],
        "roles": {
            "realm": [
                {
                    "name": "admin",
                    "composite": false,
                    "clientRole": false,
                    "containerId": "{{ $realm.name }}",
                    "attributes": {}
                },
                {
                    "name": "user",
                    "composite": false,
                    "clientRole": false,
                    "containerId": "{{ $realm.name }}",
                    "attributes": {}
                }
            ],
            "client": {
                {{- range $idx, $client := $realm.clients }}
                "{{ $client.name }}": []{{- if not (eq $idx (sub (len $realm.clients) 1)) -}},{{- end }}
                {{- end }}
            }
        },
        "users": [
            {
                "username": "admin",
                "enabled": true,
                "totp": false,
                "emailVerified": false,
                "credentials": [],
                "disableableCredentialTypes": [],
                "requiredActions": [],
                "realmRoles": [
                    "admin",
                    "uma_authorization",
                    "offline_access"
                ],
                "clientRoles": {
                    "account": [
                        "view-profile",
                        "manage-account"
                    ]
                },
                "notBefore": 0,
                "groups": []
            },
            {
                "username": "user",
                "enabled": true,
                "totp": false,
                "emailVerified": false,
                "credentials": [],
                "disableableCredentialTypes": [],
                "requiredActions": [],
                "realmRoles": [
                    "user",
                    "uma_authorization",
                    "offline_access"
                ],
                "clientRoles": {
                    "account": [
                        "view-profile",
                        "manage-account"
                    ]
                },
                "notBefore": 0,
                "groups": []
            }
        ],
        "clients": [
            {{- range $clientIdx, $client := $realm.clients }}
            {
                "clientId": "{{- $client.name }}",
                "surrogateAuthRequired": false,
                "enabled": true,
                "alwaysDisplayInConsole": false,
                "clientAuthenticatorType": "client-secret",
                "redirectUris": [
                    {{- range $idx, $redirectUri := $client.redirectUris }}
                    "{{ $redirectUri }}"{{- if not (eq $idx (sub (len $client.redirectUris) 1)) -}},{{- end }}
                    {{- else }}
                    "http://change.me/*"
                    {{- end }}
                ],
                "webOrigins": [
                    {{- range $idx, $webOrigin := $client.webOrigins }}
                    "{{ $webOrigin }}"{{- if not (eq $idx (sub (len $client.webOrigins) 1)) -}},{{- end }}
                    {{- else }}
                    "http://change.me"
                    {{- end }}
                ],
                "notBefore": 0,
                "bearerOnly": false,
                "consentRequired": false,
                "standardFlowEnabled": true,
                "implicitFlowEnabled": false,
                "directAccessGrantsEnabled": true,
                "serviceAccountsEnabled": false,
                "publicClient": true,
                "frontchannelLogout": false,
                "protocol": "openid-connect",
                "attributes": {
                    "saml.assertion.signature": "false",
                    "saml.force.post.binding": "false",
                    "saml.multivalued.roles": "false",
                    "saml.encrypt": "false",
                    "saml.server.signature": "false",
                    "saml.server.signature.keyinfo.ext": "false",
                    "exclude.session.state.from.auth.response": "false",
                    "saml_force_name_id_format": "false",
                    "saml.client.signature": "false",
                    "tls.client.certificate.bound.access.tokens": "false",
                    "saml.authnstatement": "false",
                    "display.on.consent.screen": "false",
                    "saml.onetimeuse.condition": "false"
                },
                "authenticationFlowBindingOverrides": {},
                "fullScopeAllowed": true,
                "nodeReRegistrationTimeout": -1,
                        "protocolMappers": [
                            {{- range $idpIdx, $idp := $realm.identityProviders }}
                            {{- range $mapperIdx, $idpMapper := $idp.mappers }}
                            {{- if eq $idpMapper.type "adfs-group"}}
                            {{- if not (eq $idpIdx 0) -}},{{- end}}
                            {
                                "name": "{{ $idp.name }}-adfs-groups-to-roles",
                                "protocol": "openid-connect",
                                "protocolMapper": "oidc-usermodel-attribute-mapper",
                                "consentRequired": false,
                                "config": {
                                "aggregate.attrs": "true",
                                "userinfo.token.claim": "false",
                                "multivalued": "true",
                                "user.attribute": "{{ $idp.name }}-adfs-groups",
                                "id.token.claim": "true",
                                "access.token.claim": "true",
                                "claim.name": "realm_access.roles",
                                "jsonType.label": "String"
                                }
                            }{{- end }}
                            {{- end }}
                            {{- end }}
                        ],
                "defaultClientScopes": [
                    "web-origins",
                    "role_list",
                    "profile",
                    "roles",
                    "email"
                ],
                "optionalClientScopes": [
                    "address",
                    "phone",
                    "offline_access",
                    "microprofile-jwt"
                ]
            }{{- if not (eq $clientIdx (sub (len $realm.clients) 1)) -}},{{- end }}
            {{- end }}
        ],
        "identityProviders": [
            {{- range $idpIdx, $idp := $realm.identityProviders }}
            {
                "alias": "{{ $idp.name }}",
                "displayName": "{{ $idp.displayName | default $idp.name }}",
                "providerId": "saml",
                "enabled": true,
                "updateProfileFirstLoginMode": "on",
                "trustEmail": false,
                "storeToken": false,
                "addReadTokenRoleOnCreate": false,
                "authenticateByDefault": false,
                "linkOnly": false,
                "firstBrokerLoginFlowAlias": "first broker login",
                "config": {
                "hideOnLoginPage": "",
                "validateSignature": "true",
                "samlXmlKeyNameTranformer": "KEY_ID",
                "signingCertificate": "{{ $idp.signingCertificate }}",
                "postBindingLogout": "true",
                "nameIDPolicyFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName",
                "postBindingResponse": "true",
                "singleLogoutServiceUrl": "{{ $idp.singleLogoutServiceUrl }}",
                "backchannelSupported": "",
                "signatureAlgorithm": "RSA_SHA256",
                "wantAssertionsEncrypted": "",
                "xmlSigKeyInfoKeyNameTransformer": "CERT_SUBJECT",
                "useJwksUrl": "true",
                "wantAssertionsSigned": "",
                "postBindingAuthnRequest": "true",
                "forceAuthn": "",
                "singleSignOnServiceUrl": "{{ $idp.singleSignOnServiceUrl }}",
                "wantAuthnRequestsSigned": "true",
                "allowedClockSkew": "",
                "addExtensionsElementWithKeyInfo": "false",
                "encryptionPublicKey": "{{ $idp.encryptionPublicKey }}",
                "principalType": "SUBJECT"
                }
            }{{- if not (eq $idpIdx (sub (len $realm.identityProviders) 1)) -}},{{- end }}
            {{- end }}
        ],
        "identityProviderMappers": [
            {{- range $idpIdx, $idp := $realm.identityProviders }}
            {{- if and (not (eq $idpIdx 0)) (not (eq (len $idp.mappers) 0)) -}},{{- end}}
            {{- range $mapperIdx, $idpMapper := $idp.mappers }}
            {{- if eq $idpMapper.type "adfs-email"}}
            {
                "name": "{{ $idp.name }}-email",
                "identityProviderAlias": "{{ $idp.name }}",
                "identityProviderMapper": "saml-user-attribute-idp-mapper",
                "config": {
                "user.attribute": "email",
                "attribute.name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                }
            }{{- if not (eq $mapperIdx (sub (len $idp.mappers) 1)) -}},{{- end }}
            {{- else if eq $idpMapper.type "adfs-group"}}
            {
                "name": "{{ $idp.name }}-adfs-groups",
                "identityProviderAlias": "{{ $idp.name }}",
                "identityProviderMapper": "saml-user-attribute-idp-mapper",
                "config": {
                "user.attribute": "{{ $idp.name }}-adfs-groups",
                "attribute.name": "http://schemas.xmlsoap.org/claims/Group"
                }
            }{{- if not (eq $mapperIdx (sub (len $idp.mappers) 1)) -}},{{- end }}
            {{- else if eq $idpMapper.type "custom"}}
            {
                "name": "{{ $idpMapper.name }}",
                "identityProviderAlias": "{{ $idp.name }}",
                "identityProviderMapper": "{{ $idpMapper.category | default "saml-user-attribute-idp-mapper" }}",
                "config": {
                "user.attribute": "{{ $idpMapper.userAttribute }}",
                "attribute.name": "{{ $idpMapper.attributeName}}"
                }
            }{{- if not (eq $mapperIdx (sub (len $idp.mappers) 1)) -}},{{- end }}{{- end }}
            {{- end }}
            {{- end }}
        ],
        "authenticatorConfig": [
            {
                "alias": "create unique user config",
                "config": {
                "require.password.update.after.registration": "false"
                }
            },
            {
                "alias": "review profile config",
                "config": {
                "update.profile.on.first.login": "off"
                }
            }
        ]
    }{{- if not (eq $realmIdx (sub (len $.Values.realms) 1)) -}},{{- end }}
  {{- end -}}
  {{- end -}}
  {{- end -}}