{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
{{- include "keycloak.merged.ingress.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "keycloak.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-http
            port:
              number: 80
{{- include "keycloak.ingress.ingressClassName" . | nindent 2 }}
  tls:
  - hosts:
    - {{ include "keycloak.host" . }}
{{- include "keycloak.ingress.tlsSecret" . | nindent 4 -}}
{{- end }}
