# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
type: Opaque
stringData:
  adminPassword: {{ .Values.global.database.adminPassword }}
  databasePassword: {{ .Values.global.database.password }}
  truststore.jks: {{ .Values.truststore | quote }}
