apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
{{- $failOnUnsetValues := eq (toString .Values.global.failOnUnsetValues) "true" }}
{{- $defaultUnsetValue := "changeme" }}
{{- $unsetValues := list }}
{{- $adminPassword := .Values.adminPassword }}
{{- if not (and (eq $adminPassword $defaultUnsetValue) $failOnUnsetValues) }}
  {{- $adminPassword = dict "password" .Values.adminPassword "rules" .Values.global.passwordRules }}
  adminPassword: {{ $adminPassword | include "passutil.validated" | b64enc | quote }}
{{- else }}
{{- $unsetValues = append $unsetValues "adminPassword" }}
{{- end }}
{{- $databasePassword := .Values.global.database.password }}
{{- if not (and (eq $databasePassword $defaultUnsetValue) $failOnUnsetValues) }}
  {{- $databasePassword = dict "password" $databasePassword "rules" .Values.global.passwordRules }}
  databasePassword: {{ $databasePassword | include "passutil.validated" | b64enc | quote }}
{{- else }}
{{- $unsetValues = append $unsetValues "databasePassword" }}
{{- end }}
  {{- if .Values.truststore }}
  truststore.jks: {{ .Values.truststore | quote }}
  {{- end }}
{{- if and .Values.global.failOnUnsetValues (gt (len $unsetValues) 0) }}
{{- fail (printf "Values not set: %v" $unsetValues) }}
{{- end }}
