apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $keycloakPassword := dict "password" .Values.admin_password "rules" .Values.global.passwordRules }}
  keycloakPassword: {{ $keycloakPassword | include "passutil.validated" | b64enc | quote }}
  {{- $dbPassword := dict "password" .Values.global.database.password "rules" .Values.global.passwordRules }}
  dbPassword: {{ $dbPassword | include "passutil.validated" | b64enc | quote }}
  {{- if .Values.truststore }}
  truststore.jks: {{ .Values.truststore | quote }}
  {{- end }}
