{{- if and (eq .Values.global.externalDatabase.enabled true ) .Values.global.externalDatabase.ssl (or .Values.global.externalDatabase.sslCert .Values.global.externalDatabase.sslKey .Values.global.externalDatabase.sslRootCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certificates
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.externalDatabase.sslCert }}
  sslcert.crt: {{ (.Values.global.externalDatabase.sslCert | default "# Set sslcert.crt in values.yaml") | b64enc }}
  {{- end -}}
  {{- if .Values.global.externalDatabase.sslKey }}
  sslkey.pk8: {{ (.Values.global.externalDatabase.sslKey | default "# Set sslkey.pk8 in values.yaml") | b64enc }}
  {{- end -}}
  {{- if .Values.global.externalDatabase.sslRootCert }}
  sslrootcert.crt: {{ (.Values.global.externalDatabase.sslRootCert | default "# Set sslrootcert.crt in values.yaml") | b64enc }}
  {{- end -}}
{{- end -}}
