{{- range .Values.global.imagePullSecrets }}
{{- if not (kindIs "string" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-pullsecret-{{ .name }}
  labels: {{- include "keycloak.labels" $ | nindent 4 }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (printf "%s:%s" .username .password | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
{{- end -}}