{{- if and (.Values.prometheus.enabled) (.Values.prometheus.serviceMonitor.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
    {{- include "common.status-monitor.labels" $ | nindent 4 }}
    {{- include "keycloak.status-monitor.labels" $ | nindent 4 }}
    interface: metrics
spec:
  type: ClusterIP
  selector: {{ include "keycloak.selector" $ | nindent 4 }}
  ports:
  {{- if .Values.prometheus.httpMetricsEnabled }}
  - name: metrics-http
    port: 8080
    protocol: TCP
    targetPort: http
  {{- end }}
  - name: metrics-mgmt
    port: 9000
    protocol: TCP
    targetPort: mgmt
{{- end -}}
